server:
  port: 8081

spring:
  application:
    name: logistics-service
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:13306/logistics?serverTimezone=GMT
    username: root
    password: root

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: logistics-service
      auto-offset-reset: earliest

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8082/eureka/
    healthcheck:
      enabled: true