server:
  port: 8090
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cckevincyh/spring-cloud-demo.git
          search-paths: 'cloud-config'
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/