server:
  port: 9903

# 指定服务名称
spring:
  application:
    name: logistic-server

eureka:
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    service-url:
      # 配置注册中心地址
      defaultZone: http://localhost:9901/eureka