server:
  port: 8764

spring:
  application:
    name: service-booking-creation
  datasource:
    username: root
    password: TaylorYan123
    url: jdbc:mysql://localhost:3306/creation
    driver-class-name: com.mysql.cj.jdbc.Driver
  activemq:
    broker-url: tcp://localhost:61616
    in-memory: true
    pool:
      enabled: false
    user: admin
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  endpoint:
    health:
      show-details: always